
DIRECTORIES:
  working_directory: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo"
  rvhaplo_results: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/results_RVHaplo"
  sequencing_summary: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/sequencing"
  fastq_file: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/reads"

FILES:
  reference_file: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/ref/BF1.fasta"

config_seqkit:
  cut: 0

summary_file:
  presence: True


