
DIRECTORIES:
  working_directory: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo"
  rvhaplo_results: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/results_RVHaplo"
  sequencing_summary: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/sequencing"
  fastq_files: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/reads"
  fast5_files: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/fast5"

FILES:
  reference_file: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/ref/BF1.fasta"
  all_refs_file: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/ref/refs.fasta"
  all_refs_CP: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/ref/seq_CP.fasta"


PARAMS:
  RVHaplo:
    threads: 32
  bwa_mem:
    threads: 16

config_seqkit:
  cut: 0

summary_file:
  presence: True


