
DIRECTORIES:
  working_directory: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo"

FILES:
  fastq_file: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/reads/mix50.fastq"
  reference_file: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/ref/BF1.fasta"

