DIRECTORIES:
  working_directory: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo"
  rvhaplo_results: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/results_RVHaplo"
  sequencing_summary: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/sequencing"
  fastq_files: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/reads"

FILES:
  reference_file: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/ref/BF1.fasta"
  all_refs_file: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/ref/refs.fasta"
  all_refs_CP: "/scratch/test_RYMV/snakemake/snakemake_rvhaplo/ref/seq_CP.fasta"


PARAMS:
  RVHaplo:
    threads: 32
  bwa_mem:
    threads: 16

FILTER_READS:
  minimum_length: 0

SEQUENCING_SUMMARY:
  presence: True


